[package]
name = "stlc2"
version = "0.1"
lean_version = "leanprover-community/lean:3.50.3"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "940d371319c6658e526349d2c3e1daeeabfae0fd"}
